# Ubuntu on VirtualBox
# provisioned for TypeScript

# https://docs.vagrantup.com.
Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.provision "chef_zero" do |chef|
    chef.add_recipe "vagrant_typescript"
  end

  config.vm.provision "file", source: "~/.gitconfig", destination: ".gitconfig"

end
