# vi: set ft=ruby :
# Ubuntu on VirtualBox
# provisioned for F#

# https://docs.vagrantup.com.
Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.name = ::Dir.pwd.split(::File::SEPARATOR).last
    vb.cpus = 2
    vb.memory = 1024
  end

  config.vm.provision "chef_zero" do |chef|
    chef.add_recipe "fsharp"
    chef.add_recipe "fsharp::spacemacs"
    chef.add_recipe "fsharp::bash"
  end

  config.vm.provision "file", source: "~/.gitconfig", destination: ".gitconfig"

end
